# Generated by Django 3.0.2 on 2020-01-05 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Running'), (3, 'Returned'), (4, 'Cancelled'), (5, 'Rejected')], default=0)),
                ('application_date', models.DateField(default=datetime.date.today, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'ordering': ('-start_date',),
            },
        ),
    ]
